apiVersion: v1
kind: Pod
metadata:
  name: alpine-pod
  labels:
     app: dep3
spec:
  containers:
  - name: alpine-container4
    image: alpine
    command: ["sleep","infinity"]                                                
