apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
     app: dep10
spec:
  containers:
  - name: httpd-container10
    image: httpd
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: dep10
  ports:
  - protocol: TCP
    port: 1560
    targetPort: 80
    nodePort: 30012
