apiVersion: apps/v1
kind: Deployment
metadata: 
  name: httpd-deployment1
spec:
  replicas: 5
  selector:
    matchLabels:
      app: dep1
  template:
    metadata:
      labels:
        app: dep1
    spec:
      containers:
      - name: httpd-container1
        image: httpd:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
spec:
  type: NodePort
  selector:
    app: dep1
  ports:
  - protocol: TCP
    port: 1556
    targetPort: 80
    nodePort: 30001

