apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  labels:
     app: dep9
spec:
  containers:
  - name: nginx-container9
    image: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: dep9
  ports:
  - protocol: TCP
    port: 1559
    targetPort: 80
    nodePort: 30011
