apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment2
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dep2
  template:
    metadata:
      labels:
        app: dep2
    spec:
      containers:
      - name: nginx-container2  
        image: nginx
        ports:
        - containerPort: 80
---          
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: NodePort
  selector:
    app: dep2
  ports:
  - protocol: TCP
    port: 1557
    targetPort: 80
    nodePort: 30002

