apiVersion: v1
kind: Pod
metadata:
  name: postgres-pod1
  labels:
    app: postgres
spec:
  containers:
  - name: postgres
    image: postgres:latest  
    ports:
    - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres_user"
      - name: POSTGRES_PASSWORD
        value: "postgres_password"
      - name: POSTGRES_DB
        value: "postgres_db"
  restartPolicy: Always  
